# Generated by Django 5.2.12 on 2026-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
