# Generated by Django 5.2.12 on 2026-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_daily_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.IntegerField(choices=[(1, "Soft"), (2, "Hard")], default=1),
        ),
    ]
